### ISSUE TITLE
Update scrapyd-requirements.txt in kingfisher-scrape

### ISSUE THREAD

**Issue by romifz** [open-contracting/deploy#126]
To be in sync with https://github.com/open-contracting/kingfisher-scrape/blob/master/requirements.txt

@odscjames catched this. Should we have a documented procedure on how to update this file?

**Comment by jpmckinney** [comment]
I think the logic is to be in sync with https://github.com/open-contracting/kingfisher-scrape/blob/master/requirements.in, removing scrapyd-client or Scrapy, and adding scrapyd.

Let's just add a comment to requirements.in to explain this logic and the file to edit in the deploy repo.

**Comment by odscjames** [comment]
We could update salt to just use the requirements.txt file from Scrape repository when installing the VirtualEnv for Scrapyd. This would mean we would not have any issues with keeping the 2 requirements files in Sync. 

It would mean we would have to add scrapyd to https://github.com/open-contracting/kingfisher-scrape/blob/master/requirements.in , but I don't think that would cause any problems. (We should put a comment saying why Scrapyd is in that file, so it's not accidentally removed.)

**Comment by jpmckinney** [comment]
We'd be unnecessarily installing scrapyd-client on the server, but I think that's okay.

Let's go ahead with just using requirements.txt. We should update the "Install Scrapyd" step in Kingfisher Scrape's docs as well.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix duplicate Scrape requirements files](https://trello.com/c/8tj5GaO2/202-fix-duplicate-scrape-requirements-files)

**Comment by odscjames** [comment]
https://github.com/open-contracting/deploy/blob/master/salt/ocdskingfishercollect.sls no longer checks out the Git repo - this is because people now upload spiders from local machines. We'll have to put that back, so we can get the requirements file from there.

Just noticed: scrapyd isn't in https://github.com/open-contracting/deploy/blob/master/salt/ocdskingfishercollect/scrapyd-requirements.txt  any more. It was removed by https://github.com/open-contracting/deploy/commit/c39e59338c7946d1842307a8ea875d3049c4cc67#diff-d56902b39a0997a4ca187fda22fd8578 I assume this was an accident. It we try and rebuild the server before fixing this issue, this would cause an issue.

First Pull Request done: https://github.com/open-contracting/kingfisher-collect/pull/488

**Comment by jpmckinney** [comment]
> https://github.com/open-contracting/deploy/blob/master/salt/ocdskingfishercollect.sls no longer checks out the Git repo - this is because people now upload spiders from local machines. We'll have to put that back, so we can get the requirements file from there.

Why not just curl https://github.com/open-contracting/kingfisher-collect/blob/master/requirements.in ? Seems overkill to clone the repo (which users might then think is relevant).

Yes, looks like removing `scrapyd` was in error.

**Comment by odscjames** [comment]
Done https://github.com/open-contracting/deploy/commit/5a028c65945160bc8cf1a06ca97d1fc94dc0f65e

Deployed to test, and as there were some small version bumps restarted Scrapyd too.

**Comment by odscjames** [comment]
This should be ready to close as soon as the tiny pull request above to remove a bad comment is merged

**Comment by jpmckinney** [comment]
Approved above, so closing.
