### ISSUE TITLE
More Physical Disk Prometheus alerts?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#133]
Currently we monitor 
* `smartmon_device_smart_healthy` probably to late if this flips but still
* `smartmon_wear_leveling_count_value` less then certain values. This starts at 100 and counts down to 0 as a percentage of estimated life left. 

Can we think of any other alerts that would tell us a disk is about to suddenly fail while it still has a high `smartmon_wear_leveling_count_value` left?

I'm told this is still hard to work out; apparently there just isn't enough real world data on real world failures yet to be sure.

**Comment by jpmckinney** [comment]
Who might be able to answer your question? We can also leave it to Dogsbody.

**Comment by JimACarter** [comment]
smartmon_device_smart_healthy is worth continuing to monitor, it will alert us once the drive fails or up to 24 hours beforehand.  This is still useful given the kingfisher servers have software raid1.  In the unlikely event that the drives fail at the same time we'd still need to restore data from backups.

I'd need to look into smartmon_wear_leveling_count_value and how it's calculated if you're happy for me to spend some time on this.  Without having looked into it my main concern is as to where we'd set the alert threshold.  Ideally we want to investigate a problem or be able to go and fix it straight away when an alert goes off.  The current value of 50 seems fine if you're happy delaying the discussion until then.

If you want to monitor more metrics to try to catch failures earlier I'd look to add SMART 5, 187 and 197.  Of the 5 metrics listed on https://www.backblaze.com/blog/hard-drive-smart-stats/ as indicating impending disk drive failure these three are already being collected by Prometheus.

**Comment by jpmckinney** [comment]
@JimACarter Let's add alerts for the metrics you suggest, and I'm happy for you to spend some time looking into the threshold for smartmon_wear_leveling_count_value :)

**Comment by JimACarter** [comment]
We've looked into this and are not sure that it's worth alerting based on 177 smartmon_wear_leveling_count_value.  Once it reaches 0% it indicates that the device is expected to be worn out but I can't find any guidance on at what point you'd want to replace the drive.  If you do want to keep an alert for it I'd suggest 5% rather than the current 50% as this would then match the internal threshold.  Was there a specific reason you wanted to use this attribute?

As you've got Samsung SSDs it might be worth also monitoring the 4 attributes they say are the most important on https://image-us.samsung.com/SamsungUS/b2b/resource/2016/05/31/WHP-SSD-SSDSMARTATTRIBUTES-APR16J.pdf 
- 179 Unused Reserved block Count
- 181 Program fail Count
- 182 Erase fail Count
- 183 Runtime bad Count
We'd then set the threshold at 10% as they recommend replacing the drive as soon as possible after that point.
Of these only smartmon_erase_fail_count_total_value is currently being picked up but it looks like we could update smartmon_attrs to catch the others.

The current test for health might not report as expected because a short test is not being regularly run.  I suggest we configure smartd (which is already running) via /etc/smartd.conf to have it do this.

**Comment by jpmckinney** [comment]
Thanks, @JimACarter! I'm happy for you to make the changes needed to track the most important attributes, and to change the current alerts (or remove them if their utility is unclear).

**Comment by JimACarter** [comment]
Closing this as we've updated alerting.

In order to add some of the extra smart alerts I needed to edit node-exporter-textfile-collector-scripts to have it send some extra data.  I've got an open PR https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/pull/54.  Which would allow https://github.com/open-contracting/deploy/commit/f8fac266ae77f0602e12fef030d1943a1af2f0d7 to be rolled back.

**Comment by JimACarter** [comment]
Closing this as we've updated alerting.

In order to add some of the extra smart alerts I needed to edit node-exporter-textfile-collector-scripts to have it send some extra data.  I've got an open PR https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/pull/54.  Which would allow https://github.com/open-contracting/deploy/commit/f8fac266ae77f0602e12fef030d1943a1af2f0d7 to be rolled back.
