### ISSUE TITLE
Kingfisher Archive: Disk clean up

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#150]
Do we still need any of these?

* /root
    * [x] 2019-nov-main-server-backup (961G)
    * [x] 2019-dec-main-server-backup (70GB)
* /home/ocdskingfisher
    * [x] ocdskingfisher.dump (March 2019)
    * [x] ocdsdata.dump (March 2019)
* /home/archive
    * [ ] ocdsdata_archive (March 2019, 8GB)
    * [ ] ocdskfs-old-data/old-data (August 2019, 69GB)
    * [ ] ocdskingfisher-user-data/data (August 2019, 72GB).

I assume the `analysis` and `ocdskfp` home directories only exist from when Kingfisher was deployed to this server, and can be deleted.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher Archive: Disk clean up](https://trello.com/c/oX3GmBvL/224-kingfisher-archive-disk-clean-up)

**Comment by robredpath** [comment]
I've reviewed the contents of /home/archive, as I believe I created those directories. 

It's hard to say to what degree we 'need' the data in those directories. I don't see any sign that it's in regular use as part of anyone's job right now, however the purpose of the archive was to provide some degree of an historical record of data, in case we ever wanted to do change-over-time analysis, or suspected that records had been altered. The reason that /home/archive/ocdsdata_archive is so much smaller is that I compressed the directories massively, so that the data wasn't lost, but took up a trivially small amount of space. The archive server isn't just a backup server, after all. 

@jpmckinney I'm happy to remove any of the data in /home/archive if you're happy that we will never want to do that kind of analysis. Otherwise, I'd be happy to compress all the data there in the same way, and leave an appropriate README to express its purpose. It's likely to be small enough to handle on a personal machine once compressed - in the order of 10GB or so - so could be handled manually when we migrate away from the archive server in time. 

I don't think we need any of the other files, either, but I'll check this with others this week. 

> I assume the analysis and ocdskfp home directories only exist from when Kingfisher was deployed to this server, and can be deleted.

I think that's true as well. But, again, I'll check with others this week.

**Comment by jpmckinney** [comment]
@robredpath Can you explain the differences (e.g. in terms of provenance or otherwise) between ocdsdata_archive, ocdskfs-old-data and ocdskingfisher-user-data?

**Comment by odscjames** [comment]
> /root/2019-nov-main-server-backup (961G)
> /root/2019-dec-main-server-backup (70GB)

Late Nov 2019 was the server crash when all our hard disks went. So I think these are backups related to that and can now be just removed.

> /home/ocdskingfisher/*.dump

I'm not sure what these are. There was an attempt to set up replication at one point that was dropped, could be to do with that. But in any case, I think we can say remove them. 

> /home/archive/ocdsdata_archive
> /home/archive/ocdskfs-old-data/old-data
> /home/archive/ocdskingfisher-user-data/data

These are all from the first version of Kingfisher, before the rewrite that separated scrape and process. (metadb.sqlite files on disk are the giveaway). The first one is compressed files, the others not.

> I also see some overlap between ocdskingfisher-user-data and the actively-updated data directory (e.g. some afghanistan_records folders) 

Just because both have afghanistan_records doesn't mean there is overlap. The same source may have been run multiple times. Looking at the dates for each afghanistan_records, one runs 2018-10-03 to 2019-02-07 and the other runs 2019-02-07 to 2020-01-23. The ones on 2019-02-07 have different times, oddly. 

> Do we still need any of these?

Let me comment on that shortly

**Comment by odscjames** [comment]
> Do we still need any of these?

To build on Rob's comment,

> however the purpose of the archive was to provide some degree of an historical record of data, in case we ever wanted to do change-over-time analysis, or suspected that records had been altered. 

Because of this I would suggest this isn't the place to make any decisions - I'd suggest we remove the random data (backup and dump). For all data that is organised by source and date, we make sure we migrate them to the new system that we will be setting up as we work on the task "Move to S3 or equiv and shutdown archive server".

I see issues of removing specific publishers totally, or removing old data sets, or removing some data sets if we have many for the same publisher as issues that will apply to our new system too, and also as issues that the analysts can help us clarify user needs on - so I'd move any such considerations to a future conversation around our new system.

**Comment by jpmckinney** [comment]
We've had those discussions: #153 #154 The data retention policy is here: https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-process.html#data-retention-policy

Now, to apply the policy, I need to know more about the provenance of:

>> /home/archive/ocdsdata_archive
>> /home/archive/ocdskfs-old-data/old-data
>> /home/archive/ocdskingfisher-user-data/data

> These are all from the first version of Kingfisher, before the rewrite that separated scrape and process. (metadb.sqlite files on disk are the giveaway). The first one is compressed files, the others not.

Okay, but how are they different? Are they different in terms of provenance (one old directory versus another)? In terms of time (one copied over at one time versus another)? Can nothing be inferred from the directory names?

**Comment by robredpath** [comment]
So, I have:
- Uncompressed the contents of `/home/archive/ocdsdata_archive`
- Run a find to order the directories by date order - see https://gist.github.com/robredpath/4b0c6b7c24c97c805014ea67561c70e7 for the results

It looks broadly like the directories follow on from each other - `ocdsdata_archive`, then `ocdskingfisher-user-data`, then `ocdskfs-old-data` . The directories are consistently named. 

I *think*, therefore, that we've got enough to meaningfully archive this data. We know the name of the source and the date of creation for each directory of data. Some of it will certainly require different handling because it came from a different system, but that's something we can document. 

@jpmckinney @odscjames shall we, then, run through each of these directories, and:
- Delete any that have a corresponding entry already in `/home/archive/data`
- Create a tarball for each one that doesn't have a corresponding entry already, in the manner of the output of the current version of the kf-archive script ?

**Comment by odscjames** [comment]
> Okay, but how are they different? Are they different in terms of provenance (one old directory versus another)? In terms of time (one copied over at one time versus another)? Can nothing be inferred from the directory names?

I wouldn't remember enough to be able to answer with certainty, I'm sorry.

> The data retention policy is here: https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-process.html#data-retention-policy

Thanks, that's good to read.

In terms of the 3 clauses (Clean, Complete, Periodic): The first 2 are hard to evaluate just from the data. In terms of clean, some errors may be things the analysts note as "bad data" in their report while still continuing to review the rest of the data. Other errors may mean that Analysts write a  whole collection off. We can't know just from what we have on disk. This is true of current runs we save too. Complete is also hard to tell, though we can take out the sample ones easily at least. 

I'd maybe suggest putting this on hold until we do https://github.com/open-contracting/kingfisher-archive/issues/10 - which I think we want to talk about next anyway. That's seems better anyway (if we de-active the archive server THEN switch to S3 there is a period in the middle with no active archive) and also in working out and agreeing a plan for S3 I suspect we would go into some issues (like the above) that might help resolve this one.

**Comment by jpmckinney** [comment]
> The first 2 are hard to evaluate just from the data

Yes, these would have to be supported by the Scrapyd logs (see https://github.com/open-contracting/deploy/issues/153#issuecomment-662226711 and https://github.com/open-contracting/deploy/issues/135), and in any case rely on either human input or on "good-enough" automatic criteria. I've added clarification to the "Clean" point, which is about errors in data *collection* not in the data *itself* – so it's not an issue of "bad data".

I don't understand why this would be put on hold in favor of open-contracting/kingfisher-archive#10. It's better to take this opportunity to figure out a good process for identifying the data to archive, than to start sending data to S3 without having first figured that out...

Anyway, I think I have all the information I'll get about the existing data, so I can make progress on this issue and  https://github.com/open-contracting/deploy/issues/153#issuecomment-662226711

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Archive to S3 and decommission server](https://trello.com/c/LSzAt3nw/234-archive-to-s3-and-decommission-server)

**Comment by jpmckinney** [comment]
Cleanup log (will be continuously updated):

* Reduce unnecessary file hierarchy (e.g. ocdsdata_archive/data -> ocdsdata_archive)

## ocdsdata_archive

* Decompress .tar.xz files (performed earlier by @robredpath)
* Check the sizes of samples: `find . -type d -name '*_sample' -exec du -h {} \;`
* Delete samples: `find . -type d -name '*_sample' -exec rm -rf {} \;`
  * australia_sample (632K)
  * mexico_jalisco_sample (1.9M)
  * moldova_sample (51M)
  * paraguay_dncp_sample (204K)
  * paraguay_hacienda_sample (240K)
  * uganda_sample (112K)

**Comment by jpmckinney** [comment]
## Apply criteria

* Check the sizes of samples: `find . -type d -name '*_sample' -exec du -h {} \;`
* Delete samples: `find . -type d -name '*_sample' -exec rm -rf {} \;`
  * australia_sample (632K)
  * mexico_jalisco_sample (1.9M)
  * moldova_sample (51M)
  * paraguay_dncp_sample (204K)
  * paraguay_hacienda_sample (240K)
  * uganda_sample (112K)
* Find directories without metadb.sqlite3 (none found): `find -mindepth 2 -type d -exec test ! -e {}/metadb.sqlite3 \; -print`
* Find directories with 0 or 1 files: `find -mindepth 2 -type d -exec sh -c 'test $(ls {} | wc -l) -le 1' \; -print`
* Delete directories with only metadb.sqlite3 files:
  * afghanistan_records/2019-02-07-14-32-52
  * chile_compra/2019-03-18-12-46-51
  * honduras_sefin/2018-12-24-14-51-32
  * indonesia_bandung/2019-03-13-14-38-40
  * local_load/2018-11-27-12-12-19
  * local_load/2018-11-27-12-12-58
  * mexico_jalisco/2019-03-27-14-30-24
  * paraguay_dncp/2018-11-20-14-01-38
  * stralia_nsw/2019-01-16-16-51-49
  * taiwan/2019-01-15-18-28-20
  * uk_contracts_finder/2018-12-06-12-55-19
  * uruguay/2018-10-01-12-58-58
  * uruguay/2019-01-15-18-06-23
* Look what's in the smallest directories (looks fine): `ls $(du */* | sort -n | head | cut -f2 | xargs)`

----

IN PROGRESS:

* Compare the size and frequency of collections: `find . -mindepth 2 -type d -exec du -h {} \; | sort`
* Within a given period:
  * Compare the number of errors in metadb.sqlite3 ("clean")
  * Compare the sizes ("complete")
* Keep the earliest clean, complete collection within a given year. Delete:
  * mexico_administracion_publica_federal:
    * Keep 2018-06-14-13-58-17 (3.1G)
    * Delete 2018-08-15-20-51-44 (3.2G)
  * uk_contracts_finder:
    * Keep 2018-06-07-13-17-30 (615M)
    * Delete 2018-08-13-20-44-23 (662M)
    * Delete 2018-08-15-18-45-48 (664M)

**Comment by jpmckinney** [comment]
Done! See spreadsheet for determinations of what to keep.
