### ISSUE TITLE
OCDS DRT: uWSGI harakiri and limit-as settings

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#151]
Recently, we saw CPU and RAM peaks in Prometheus, which likely means a user uploaded a very large file.

The process was killed after 30 minutes due to uWSGI's harakiri setting in pillar/cove_pillar.sls. Should we set a longer timeout, or should users just not be uploading such large files?

Also, limit-as was set to 12GB out of 16GB (75%). The server is now 8GB, so I set it to 6GB. What is an appropriate policy for this setting?

**Comment by jpmckinney** [comment]
Adding comments from Jim Carter (Dogsbody):

> It depends on what you're expecting users to do.  Was the file uploaded here many times larger than you'd expect it to be?  How are users informed of the error if they hit this timeout?


> 75% seems like an appropriate value, that way there's some spare for other processes and the alert at 80% shouldn't regularly be being triggered.

**Comment by Bjwebb** [comment]
I think both the limits are based on very rough ideas of what we thought users were doing.

The 30-minute limit is based on the assumptions that (each of these may want revisiting):
* If something hits that limit, its unlikely to finish anyway due to memory issues
* Users are unlikely to keep the tab open longer than 30 minutes
* Processes may stick around after a user closes a tab, so we need to do something actively to kill those. (I've not properly checked what happens with a closed connection).

The 75% limit was based on [each request having a separate process](https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/uwsgi/cove.ini#L30-L31), which I think [has changed](https://github.com/open-contracting/deploy/blob/master/salt/uwsgi/django.ini). With separate processes, the limit is intended to reduce the impact of one large request on other's smaller requests. The number is based on the observation that most small requests are well under 25%.

**Comment by jpmckinney** [comment]
Thanks for confirming the reasons for the harakiri and limit-as settings. I think those assumptions are still correct. We can revisit if we get more frequent out of memory alerts.

The thread limit hasn't changed for CoVE: https://github.com/open-contracting/deploy/blob/master/salt/uwsgi/includes/cove.jinja#L8
