### ISSUE TITLE
Explore options for partial deployments

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#157]
We sometimes only want to deploy one of Kingfisher Collect, Process or Views.

Right now, we can only deploy the entire server using Salt. This means that if there is a long running crawl, or if there is a long-running SQL query, we can't update the other components.

This issue is to look into options for automating partial deployment. (We can deploy individual services manually by doing the steps that Salt would do, but that's error-prone.)

**Comment by RobHooper** [comment]
We can always run salt like this `./run.py 'hostname' state.apply kingfisher-collect`.
And that should run everything in [kingfisher-collect.sls](https://github.com/open-contracting/deploy/blob/master/salt/kingfisher-collect.sls)
Perhaps also using groups, we could turn this into a process we can document in the wiki.

The risk with this is that it ignores top.sls and will apply the state to a server regardless of if we want it to run there or not. (which could be mitigated by using groups as suggested above).

I like the current approach of applying everything because it ensures that servers stay in line with the deploy repo.
The current "full deployment" approach has the added benefit that if anything isn't applied, the next deployment will apply it.

A potential alternative solution to address these risks is to write custom deployment python scripts for these specific deployments (Kingfisher Collect, Process and Views). We could script it to detect which servers have these services installed and run a partial deployment only on them.

**Comment by jpmckinney** [comment]
I've changed this to a documentation issue.

Where is the documentation on groups?

A partial deployment should be a rare occurrence, but in cases where we don't want to interrupt a long-running process, it's good to have a documented approach.

**Comment by RobHooper** [comment]
I was thinking that we could use either nodegroups or set a pillar parameter for "role" and use that as the target.

Testing this however it seems that these advanced targetting features don't work in a masterless `salt-ssh` only set ups like ours.

https://docs.saltstack.com/en/latest/ref/cli/salt.html#target-selection
https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html

**Comment by jpmckinney** [comment]
I've documented how to deploy a specific state file. Regarding nodegroups, etc. we can discuss in #221.

**Comment by jpmckinney** [comment]
To date, there are just a few [things to consider](https://ocdsdeploy.readthedocs.io/en/latest/deploy/setup.html#check-if-kingfisher-is-busy) when deploying to the data support team's internal server ("kingfisher"). In order to decide whether to perform a partial deployment, a maintainer would have to complete the same steps – the only difference is that they wouldn't have to wait and can just do a partial deployment. That said, waiting has not interfered with our day-to-day work.
