### ISSUE TITLE
Handle empty SSH Key files

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#164]
There is currently an error during the `cove.sls` deployment setting up SSH keys.
It is because the `salt://private/authorized_keys/root_to_add_cove` file is currently empty.

Ideally, the salt code would be able to identify that this file is empty and skip it.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle empty SSH Key files](https://trello.com/c/KpDX3X7R/270-handle-empty-ssh-key-files)

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle empty SSH Key files](https://trello.com/c/KpDX3X7R/270-handle-empty-ssh-key-files)

**Comment by odscjames** [comment]
I don't think there is an easy answer here:

A)

Check the source file before running the Salt state?

I don't think salt lets you check the contents of a **local** file before running a command. What we want is "Onlyif" option, but one that runs locally not on the server. I don't think it exists.

Could we maybe write some Jinja tags to check then just wrap the salt in a Jinja if? Maybe, but seems complex and brittle based on changes to local setup (which come to thing of it, is probably why they don't let you do "onlyif" locally :smile: )

B) 

Allow certain types of error?

The error we see is 

    No keys detected in salt://private/authorized_keys/root_to_add_kingfisher. Is file properly formatted?

If we could allow this error we could just skip this, but

* there may be other error states with that message we want to see
* I'm not sure we can do this anyway

C) 

Possible solution:

The 3 files that might be empty are: 
* salt/private/authorized_keys/root_to_add_cove (Used in salt/cove.sls )
* salt/private/authorized_keys/root_to_add_kingfisher (Used in salt/ocdskingfisher.sls )
* salt/private/authorized_keys/root_to_add_toucan (Used in salt/toucan.sls )

As these 3 files are used in 3 very clear and distinct places, we could just stick a comment at the top of each SSH file, something like:

     # This file is used in the salt command in _________________
     # If this file has no SSH keys, comment out the salt command to avoid errors.
     # If this file has SSH Keys, comment back in the salt command so it actually is used.

D)

Possible solution:

Generate a dummy key, throw away the private part, add the public part to all files with an appropriate comment? Then every file will always have a key in it :smile: 

E)

Possible solution:

Take out ssh_auth.present, instead add file to server, then use a cmd.run on server to check state of file before trying to add it.

Note that because of comments, an file with no keys is not empty, so the check needs to be carefully done.

F) 

Possible solution:

New pillar variable: "additional_root_ssh_key_files_to_add_list", empty list by default. Have source files that are per person/key, use per server pillar variables to add the right files to the right server.

Take out the 3 special salt states, have a general salt state in salt/core/init.sls with a Jinja loop that adds them.



Personal preference) 

Given size of problem, I'd prefer to just do C or D. Tho F does has the nice side effect of making it easy to add extra SSH keys to any server with very little work. But not E - using ssh_auth.present is nice.

**Comment by jpmckinney** [comment]
I think Dogsbody is planning on having each person's SSH keys in separate files (rather than one big file), and then having the Salt state list the appropriate files. This might make it easier to update a single person's SSH keys.

**Comment by jpmckinney** [comment]
The new code still requires changing a single person's SSH key in multiple places if they have access to multiple servers, but this is just a little more labor – not a problem.

**Comment by jpmckinney** [comment]
I guess one option is for Pillar to set paths to public keys, and then for Salt to load those paths (e.g. using one of these functions https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#gather-external-data).
