### ISSUE TITLE
Hostname standardisation 

### ISSUE THREAD

**Issue by RobHooper** [open-contracting/deploy#172]
Currently there are a number of different hostname layouts all subtly different. It would be good to standardise this. 

We normally set up the following standard:
* Abbreviated name
* Iterating number
* Customer domain
For example `ocp0.open-contracting.org `

This means that each server has a unique name, no information leakage about what it does, no hard requirements for what it hosts.
For example, you can't really repurpose the `prometheus.default.` server to do anything different.

We need to work out what OCP's requirements are. Food for thought:
* Should we be setting the environment in the hostname (live / dev) 
* Do we have a requirement to know what servers are doing by looking at the hostname
* Do we want to use open-contracting.org or a dedicated hostname for servers
* We can easily rebuild servers with salt so will we ever repurpose an existing server? (different answers for bytemark vs hetzner)
* Is there a requirement to know the location of a server from the hostname?
* Also consider issue #115 - updating hostnames in the roster.
 

Few side notes:
It will be a bit tricky to implement a new standard against the current servers so I recommend that once defined we build new servers to this spec and slowly migrate.

Once we know what hostname standard we're using configuring the hostname should be automated in salt.
This will address the issue where a `.open-contracting.org` hostname is set up but the server doesn't use it because it is configured for `.uk.bigv.io`.

**Comment by jpmckinney** [comment]
I'm happy with servers being named ocp00.open-contracting.org, ocp01.open-contracting.org, etc. At other organizations I've seen servers named after flowers, Shakespeare characters, etc. – they were never semantic.

For Hetzner, we have A records on GoDaddy like process1.kingfisher.open-contracting.org or archive0.kingfisher.open-contracting.org. We can change those A records to the above format, and update the CNAMEs that point to them.

For Bytemark, we can shutdown servers (nothing is critical uptime-wise), move them to the default group, change the name to the above format (ocp01.default.opencontracting.uk0.bigv.io), and make corresponding changes in GoDaddy.

Questions:

* Since Bytemark already gives a hostname, should we have an extra CNAME like ocp01.open-contracting.org to point to ocp01.default.opencontracting.uk0.bigv.io? Any advantages/disadvantages either way?
* We'll also need to change the hostnames on the servers themselves. I don't know if this is an extra challenge or if it's fairly straightforward. Let me know if there are any other places that would require changes.

As for repurposing a server, we'll more likely to start a new VPS with Bytemark. However, with Hetzner, there are setup costs and price fluctuations, so it'd be nice to reuse a server, especially since we can wipe it with their rescue system.

**Comment by RobHooper** [comment]
I recommend creating A and AAAA hostname records for the bytemark hostnames rather than using CNAMES. 
CNAMES add in an extra DNS look up that can be avoided.
With this set up we can then ignore the provided bytemark hostname and configure the servers for ocpXX.open-contracting.org. 

Then we will have a uniform hostname standard regardless of provider. 

The other benefit of ignoring the bytemark hostname is that, I quite like the separation provided by groups in the bytemark interface, I know at a glance I don't need to worry about things in the development group for example. If they are all called ocpXX.default, you just need to be more cautious.


Changing the hostname on a running system can be tricky. If there are any potential rebuilds coming down the line (#145 for instance) it would be easier to do these jobs together.

**Comment by jpmckinney** [comment]
Aha, good points! Agreed on creating A, AAAA records for Bytemark hostnames. I assume the VPS's have stable IPs over reboots, etc. – unlike PaaS like Heroku?

For the groups in Bytemark, should we open a new issue to document the approach? It's not entirely consistent, and I don't know if it makes sense to have so many groups (I don't have a strong opinion).

**Comment by RobHooper** [comment]
I haven't fully tested but as far as I'm aware Bytemark IPs don't change. 

A separate issue to discuss bytemark groups makes sense but I expect the outcome to be closely linked to this ticket.
(I expect we'll be renaming the instances/groups and it makes sense for them to match the new agreed hostname structure)

**Comment by RobHooper** [comment]
The DNS records for all Bytemark servers have been updated to directly point at the servers A and AAAA IPs.  
This was escalated due to an outage with Bytemark's DNS servers. 

Just double checking, we're both happy ocpXX.open-contracting.org (ocp01, ocp02 etc) as the new hostname standard.
Did anyone else want to input on this? otherwise I'll start documenting this standard in the wiki.

**Comment by jpmckinney** [comment]
@RobHooper I think we can proceed :)

**Comment by jpmckinney** [comment]
I'm going to create a test/staging server for a new COVID-19 procurement monitoring tool. So far, the only use case we have in terms of Bytemark groups is distinguishing development from production servers. As such, I'll just put it in the development group.

Right now, we mostly have one group per service with a single server in each, which isn't terribly useful. Going forward, I think all the production servers can go in the `default` group.

**Comment by jpmckinney** [comment]
I've created the ocp## A/AAAA records and created toucan., standard., etc. CNAME records pointing to ocp##.

I didn't change the primary Hetzner hostnames:

* process1.kingfisher A
* replica1.kingfisher A/AAAA

**Comment by jpmckinney** [comment]
@RobHooper Is there anything more to do to close this issue? I think we are leaving /etc/hosts and /etc/hostname as-is until we build new servers.

**Comment by RobHooper** [comment]
Happy resolving this now that the PR is deployed.
