### ISSUE TITLE
Configure ntp/timesyncd servers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#180]
Ideally UTC, so that it's easier to reconcile events across servers, services (like Sentry) and software (most software we write uses UTC).

**Comment by RobHooper** [comment]
We are [configuring NTP to use UTC](https://github.com/open-contracting/deploy/blob/master/salt/core/ntp.sls#L25-L26).
Or is this issue for something else?

**Comment by jpmckinney** [comment]
I think I created the issue based on the work plan document, but it was already done :)

**Comment by RobHooper** [comment]
Found some new notes, this issue was to configure which NTP servers ntp/timesyncd queries.

Currently, NTP is configured for the UK pool, this should be changed to a pool closer to our servers.
For instance, kingfisher-process and registry should query the Finland pool (fi.pool.ntp.org).
kingfisher-replica should query the Germany pool (de.pool.ntp.org).

I believe all Bytemark servers are in the UK so our default of the UK pool is best, I assume we'll use the UK Datacenter for Linode but we should support the US NTP pool if / when needed (north-america.pool.ntp.org).

https://github.com/open-contracting/deploy/blob/main/salt/core/systemd/files/timesyncd.conf

**Comment by RobHooper** [comment]
Resolved in #376
