### ISSUE TITLE
firewall: firewall.sh succeeds even if stderr is non-empty

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#202]
Not sure if something can be done: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html

**Comment by jpmckinney** [comment]
Aha, it's because of `set +eu`.

**Comment by jpmckinney** [comment]
@RobHooper I assume `set +eu` was set to avoid a scenario where 99% of the iptables commands were correctly written and then one is bad; this means iptables will end up in a mostly correct state.

However, the scenario I've encountered more frequently is that I do things like put Jinja in a file but forget to set `- template: jinja`, or I make a typo, etc. Having the command pass with "Failed: 0" in the Salt output means I don't catch the error.

Since we can login via Bytemark even if we completely mess up iptables, I think it's okay to `set -eu` throughout.

What do you think?

**Comment by RobHooper** [comment]
That is correct, the big concern is that the firewall script errors and locks everyone out using `set +eu` gives it a better chance of recovering in the case of a failure. 
I'd like to keep this script being the exception and recovering itself if it can.

One alternative I can think of is if we catch error output throughout the script and then right at the end exit with a bad status code if things have errored.

Another potential option is to use bash traps to catch the script when it errors and recover.
https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html
If we use traps, it's worth bearing in mind that we need to be cautious of docker servers because this script doesn't support docker it deliberately exits early and we wouldn't want it falling back and wiping dockers iptables settings.

**Comment by jpmckinney** [comment]
I've restored `set +eu`.

**Comment by jpmckinney** [comment]
I've added a comment to `firewall.sh` about checking the output after changing the file. That manual check should ensure we don't accidentally break the file and fail to notice.
