### ISSUE TITLE
PostgreSQL: Why is /var/lib/postgresql/11/main/recovery.conf not in Salt?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#213]
It contains the old-style hostname ``process1.kingfisher.open-contracting.org``

**Comment by RobHooper** [comment]
`recovery.conf` is generated automatically as part of replication set up. This is all documented here:
https://ocdsdeploy.readthedocs.io/en/latest/deploy/postgres.html#set-up-replication

I imagine we can swap the old hostname for the new one if we want to remove the old one.

**Comment by jpmckinney** [comment]
* I see the lines that manually add restore_command and primary_slot_name. What generates the first two lines of standby_mode and primary_conninfo?
* The file is manually generated. Should its contents not be managed by Salt? For example, the replica user's name and password are in Salt, but Salt presently has no state to update them in recovery.conf.
* Does PostgreSQL not need to be restarted on the replica after `restore_command` is added?

**Comment by RobHooper** [comment]
> I see the lines that manually add restore_command and primary_slot_name. What generates the first two lines of standby_mode and primary_conninfo?
It's `pg_basebackup -R`
> The file is manually generated. Should its contents not be managed by Salt? For example, the replica user's name and password are in Salt, but Salt presently has no state to update them in recovery.conf.

> Does PostgreSQL not need to be restarted on the replica after restore_command is added?

**Comment by RobHooper** [comment]
> I see the lines that manually add restore_command and primary_slot_name. What generates the first two lines of standby_mode and primary_conninfo?

They are generated by `pg_basebackup -R`.

> The file is manually generated. Should its contents not be managed by Salt? For example, the replica user's name and password are in Salt, but Salt presently has no state to update them in recovery.conf.

We can't automate the replica set up because it is a process rather than a state. Setting up `recovery.conf` is a key part of that.
We could possibly put something in salt to manage this file after the set up, we'll need to be careful it doesn't cause problems when we set up the next replica.
What changes will we be making that effects `recovery.conf` causing it to change? 

> Does PostgreSQL not need to be restarted on the replica after restore_command is added?

I think it does need restarting same as `primary_slot_name`.
We could move both `restore_command` and `primary_slot_name` so that they are set before `service postgresql start` is ran under item 4.

**Comment by jpmckinney** [comment]
I've updated the instructions in 7a9ce79.

The only changes requiring Salt management of recovery.conf are changes to:

* the replica user's name and/or password
* the main server's hostname

These are expected to be stable, so I just put in a comment in the commit that these values are managed manually.
