### ISSUE TITLE
DNS TTL standardisation

### ISSUE THREAD

**Issue by dogsbody-rob** [open-contracting/deploy#228]
> I noted that the `postgres-replica` DNS record currently has an hour TTL.

Can you start another PR to edit the recommended TTLs in https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html#create-dns-records? The original TTLs for A and AAAA records were 1 day 3328d1a8e3a2692379299cce46a0c5c3a2b2048b. I'm fine with whatever TTL as long as there's an explanation.

_Originally posted by @jpmckinney in https://github.com/open-contracting/deploy/issues/220#issuecomment-746757500_

**Comment by RobHooper** [comment]
Our internal DNS standards are:

Name Servers: 2 Days / 172800 

Server hostname: 1 Day / 86400 
> i.e. A records, AAAA records used for server hostnames (ocp01.open-contracting.org)

Static Sites - 4 Hours / 14400 
> i.e. www.dogsbody.com

MX records - 4 Hours / 14400 
> MX record priority
> Low - 40 (MX Backup)
> Normal - 30 (mail.domain.com)
> High - 20 (Special)

CAA Records: 1 Day / 86400
> CAA Records used for SSL validation

High Availability Sites - 5 mins / 300 (ideally, or up to 15 mins / 900 )

If not defined above - 1 hour / 3600

The most important ones for OCP are Server Hostnames, Static Sites and HA Sites.

You want DNS records to be cached for as long as you can without it effecting function. For example. if DNS records are looked up for each querty then it will slow down visitors accessing your site. On the other hand, if it is cached for too long visitors won't pick up new changes. 
Another consideration is that some DNS providers have a quota for DNS queries, I don't think our current DNS provider does this so might not be a concern.

I think that most of the OCP sites fall under "static sites", the exception to this is the postgres-readonly endpoint which we'd like to change in the case that the replica breaks. This would be better with a short TTL less than 15 mins. The quicker we can migrate over the shorter the outage. 

Also noting that DNS changes do happen, for example if we were migrating a site to a new server. In these situations we will reduce the DNS TTL as low as we can a day before the migration time so that DNS caching isn't an issue.

**Comment by jpmckinney** [comment]
What is meant by "static site"? Most servers are running applications (Django apps, Prometheus, Redash). I think the only site that is just serving files from a web server is docs.

For simplicity, maybe we go with:

* A and AAAA records: 1 day
* CNAME records (high availability): 5 min
* CNAME records: 1 hour

And the only high availability site would be postgres-readonly - right?

**Comment by RobHooper** [comment]
By static site I just mean that the site isn't moving anywhere, it is hosted in one place.

I agree, lets keep it simple, you don't need all of the standards I detailed out. I felt it was a good place to start :)

I prefer breaking down the DNS standards by purpose, like so:
* Server hostname records, A and AAAA records, TTL 1 day
* High Availability Application, CNAME, TTL 5 min
* Non-HA Application / All other records, CNAME, TTL 1 hour

This gives us room to change record types as needed in the future while preserving the caching we want. 

> And the only high availability site would be postgres-readonly - right?
That is correct

Where should this be documented? I was thinking `deploy/dns.rst`

**Comment by jpmckinney** [comment]
Sounds good!

It can either be https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html#create-dns-records, or we can move that step into its own page and link to it.
