### ISSUE TITLE
Consider separating deployments of Process and Views

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#26]
Process and Views (if https://github.com/open-contracting/kingfisher-views/issues/34 is pursued) only interact at the level of the database, i.e. Views can work with any database whose schema is the same as Process.

As such, I don't see why both should always be deployed at the time, as is currently the case.

If one of the two has a broken deployment, it shouldn't cause the other to fail, like in #24.

**Comment by odscjames** [comment]
> As such, I don't see why both should always be deployed at the time, as is currently the case.
> If one of the two has a broken deployment, it shouldn't cause the other to fail,

That's not quite how Salt works; Salt compiles all your rules into one big pot, it doesn't matter which file they come from. By default, every rule is fully parallelizeable at Salt's whim unless you explicitly give it dependency instructions. It will then run them - and if one rule is broken, it will keep running the rest.

So unless one rule depends on the other - and as you point out, Process and Views are separate so their rules don't depend on each other (from memory, shouldn't be anyway!) - we are already in a situation where just because the View part fails (as in #24) the Scrape and Process part install will still work fine.

**Comment by jpmckinney** [comment]
Aha, I misunderstood what steps had led to the failure in #24.
