### ISSUE TITLE
compilemessages isn't run for lib-cove-web any more

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/deploy#269]
compilemessages now has the `--ignore=.ve` flag: https://github.com/open-contracting/deploy/blob/main/salt/python_apps.sls#L109
This is a problem, because lib-cove-web has uncompiled messages, and relied on that command to find them where it's installed within `.ve`.

I think our options are:
1) Remove the ignore flag.
2) Work out how to run compilemessages for just lib-cove-web within .ve
3) Compile the messages on setup.py install, as we do for flatten-tool https://github.com/OpenDataServices/flatten-tool/blob/main/setup.py#L6-L27
4) Commit the compiled `.mo` files in the lib-cove-web GitHub repo. Whilst in general commiting compiled files is bad, it seems to be pretty common for compiled translations: both [django](https://github.com/django/django/blob/main/django/conf/locale/en/LC_MESSAGES/django.mo) and [sphinx](https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/locale/es/LC_MESSAGES/sphinx.mo) do it.

@jpmckinney What do you think?

**Comment by jpmckinney** [comment]
Hmm, that is not a safe assumption for lib-cove-web to make.

I think it is better to commit the MO files like Django and Sphinx do.

The MO flag was added because for another Django app, it was spending a lot of time compiling messages unnecessarily.

When gettext was originally created, platforms were perhaps more dramatically different. Now, MO files seem to be interchangeable across platforms.

**Comment by Bjwebb** [comment]
I've committed the files in https://github.com/OpenDataServices/lib-cove-web/pull/97, and added a test that the compiled files are up to date.
