### ISSUE TITLE
Do we want a backup of the database on Kingfisher live?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#3]
Tho we should be able to reload almost everything* from files on disk, it would take a while.

This came up in conversation with @kindly.

ps.* The tiny exception is explained in https://github.com/open-contracting/kingfisher-process/issues/122

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identify + implement mitigations for kingfisher-process downtime](https://trello.com/c/VjGXTBis/150-identify-implement-mitigations-for-kingfisher-process-downtime)

**Comment by jpmckinney** [comment]
#86 proposes a replication server. In case of downtime, disk failure, etc., I think we'd want a 'hot' backup (one we can quickly and easily switch over to), rather than `pg_dump` outputs that then need to be loaded into a new/restored server. If that's correct, then we can close this issue in favor of #86.
