### ISSUE TITLE
Gitmodules breaks Read The Docs

### ISSUE THREAD

**Issue by odscjames** [open-contracting/deploy#30]
https://readthedocs.org/projects/ocdsdeploy/builds/9705262/

**Comment by jpmckinney** [comment]
Sigh, looks like this won't be fixed soon: https://github.com/readthedocs/readthedocs.org/issues/4043

In https://crm.open-contracting.org/issues/4473 I proposed using Gitbook to centralize some disparate documentation (handbook, helpdesk process docs, the kingfisher repo which is just docs, etc.).

So, one option to fix this issue is to move the deploy docs to Gitbook (along with the others over time), which has the added benefits of having private pages and offering a better editing UI.

**Comment by jpmckinney** [comment]
Let's back out the gitmodules changes (allows us to keep docs next to code, makes it easier for another user to re-use the public code and their own private code without fooling around with gitmodules).

**Comment by odscjames** [comment]
https://github.com/open-contracting/deploy/pull/36
