### ISSUE TITLE
Decide whether to add a frontend for Docker management

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#300]
https://www.portainer.io

**Comment by jpmckinney** [comment]
@yolile Can you describe the biggest advantages? Maybe for easily reviewing logs?

**Comment by yolile** [comment]
The main advantage is to have a nice UI to run any docker command you want.
That includes:
- Reviewing the logs of each container
- Running commands on each container (if we ever need to do that)
- See the containers resources usage (memory, storage, etc)
- Start/stop/restart containers
- See the containers used ports, creation date, etc
- Create containers from images
- Create/pull images

It has a community version that can be installed as a docker image as well https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/

See a demo here http://demo.portainer.io/ (username `admin` password `tryportainer`)

Of course, you can do all of this by running docker commands, so it is really a nice-to-have feature rather than a must.

**Comment by jpmckinney** [comment]
Okay, let's see how it goes without, and we can re-consider later.
