### ISSUE TITLE
Consider Docker metrics for Prometheus

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#310]
https://docs.docker.com/config/daemon/prometheus/

I suppose we could then configure alerts if expected containers aren't up? This would only be relevant for containers that don't have a public web address (which would be already covered by Dogsbody's uptime monitoring). Not sure what else we could use Docker monitoring for.

**Comment by RobHooper** [comment]
Docker metrics would be nice to have. The main use-case I can think of is using the Docker stats in combination with server monitoring, e.g. comparing high memory reported on Registry with container memory stats.

Alerting on missing containers may be more complex to implement, we would need to manually state all expected containers for each server and update this as systems change. We wouldn't want false positive alerts caused by temporary containers.
How many completely unmonitored containers/services are there?

Once we are collecting these metrics we may find more use-cases. 

On the other hand, the quantity of data this will generate is currently unknown and it's impact on the Prometheus server should be considered.

**Comment by jpmckinney** [comment]
Since the metrics are 'nice-to-have' rather than should/must have, I'll remove from priority milestone.

So far, I think we've figured out why RAM usage, etc. is high without Docker monitoring, but it could help in future.

> How many completely unmonitored containers/services are there?

On ocp13 (registry) the monitored ones are data-registry-web, data-registry-static, spoonbill-web and spoonbill-static, and the other 21 are not monitored. On ocp23 (kingfisher-main), pelican-frontend-web and pelican-frontend-static are monitored, the other 15 are not.

I agree that it's too much overhead to list all expected containers – considering we haven't had an issue with containers being down. (What happens instead is that a container remains up, but RabbitMQ no longer considers it as a good consumer, so it stops sending messages to it. We've largely fixed such issues, though.)

**Comment by jpmckinney** [comment]
Hmm:

> Currently, you can only monitor Docker itself. You can't currently monitor your application using the Docker target.

https://docs.docker.com/config/daemon/prometheus/

I'll close as we don't really have a use case for monitoring individual containers anyway.
