### ISSUE TITLE
Linode IPv6 process changes documentation

### ISSUE THREAD

**Issue by dogsbody-rob** [open-contracting/deploy#409]
There are a number of changes to Linode IPv6 that we have discovered since writing the docs.

Firstly, Linode cannot provision an IPv6 /64 block to the account, a new block needs provisioning per server.
There is a new network menu in their interface to provision a block without support.
However Linode have also said that you can only have one IPv6 /64 block per account. 

We should raise a ticket with them to clarify the last point.

When the new process is known, the following pages need updating:
- [ ] https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html
- [ ] https://ocdsdeploy.readthedocs.io/en/latest/develop/update/network.html#linode

**Comment by RobHooper** [comment]
@jpmckinney after testing and discussing the IPv6 situation with Linode Support it is clear there are no perfect solutions.

The problem is that, as of this year; Linode only allow customers to provision one IPv6 block per account. This IPv6 block can only be associated with one instance at a time. 
There is a potential solution where a server is configured as a router passing IPv6 traffic to other servers in our network, however this adds a single point of failure to our entire IPv6 network so we recommend against this.

For the time being, I think we are best using the SLAAC IP for IPv6 traffic (the automatically assigned IPv6 address from Linode).
This IP will have a poor reputation due to SPAM being sent from near-by addresses. Therefore, we will need to reconfigure Postfix to use IPv4 only.

When there is a better solution we can review.

**Comment by jpmckinney** [comment]
Ok, sounds good. Do you know what the reputation is for a sample SLAAC IP?

**Comment by RobHooper** [comment]
I've checked the IPv6 addresses across the current OCP linodes and 5 out of 8 of them are listed on spam blocklists.
