### ISSUE TITLE
ocp23: pgBackrest error

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#529]
Cron <postgres@ocp23> pgbackrest backup --stanza=kingfisher-2023

```
P00  ERROR: [082]: WAL segment 00000001000009FD0000000D was not archived before the 60000ms timeout
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
HINT: run the 'start' command if the stanza was previously stopped.
```

**Comment by RobHooper** [comment]
@jpmckinney , pgbackrest timeouts like the above happen occasionally for a number of reasons and are often out of our control (such as network timeouts).
I have logged into ocp23 and reviewed the stored backups, I can see that yesterdays (07 Oct) backup failed completely and that this mornings backup ran successfully. I also cannot see evidence of any other failed backups in the past month.

Based on the above I am happy putting this down as a one off error.

The command to view stored backups:
```bash
sudo -u postgres pgbackrest info --stanza=kingfisher-2023
```

For the record, this was an incremental backup that failed, if a full backup fails it is good to re-run the full backup so that further incremental backups are faster to restore.

**Comment by jpmckinney** [comment]
Thank you!

**Comment by jpmckinney** [comment]
Added to docs: d106506f
